/*
 * MIT License
 *
 * Copyright 2021 Michael Shaw
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef OPCODES_H_
#define OPCODES_H_

#include <addrmodes.h>
#include <instructions.h>
#include <stdlib.h>

#define OPC(i, m) inscall_##i, adm_##m
#define INV       NULL, NULL

// pro tip: use regex

void *codes[] = { OPC(brk, impl),
                  OPC(ora, Xind),
                  INV,
                  INV,
                  INV,
                  OPC(ora, zpg),
                  OPC(asl, zpg),
                  INV,
                  OPC(php, impl),
                  OPC(ora, imm),
                  OPC(asl_a, A),
                  INV,
                  INV,
                  OPC(ora, abs),
                  OPC(asl, abs),
                  INV,
                  OPC(bpl, rel),
                  OPC(ora, indY),
                  INV,
                  INV,
                  INV,
                  OPC(ora, zpgX),
                  OPC(asl, zpgX),
                  INV,
                  OPC(clc, impl),
                  OPC(ora, absY),
                  INV,
                  INV,
                  INV,
                  OPC(ora, absX),
                  OPC(asl, absX),
                  INV,
                  OPC(jsr, abs),
                  OPC(and, Xind),
                  INV,
                  INV,
                  OPC(bit, zpg),
                  OPC(and, zpg),
                  OPC(rol, zpg),
                  INV,
                  OPC(plp, impl),
                  OPC(and, imm),
                  OPC(rol_a, A),
                  INV,
                  OPC(bit, abs),
                  OPC(and, abs),
                  OPC(rol, abs),
                  INV,
                  OPC(bmi, rel),
                  OPC(and, indY),
                  INV,
                  INV,
                  INV,
                  OPC(and, zpgX),
                  OPC(rol, zpgX),
                  INV,
                  OPC(sec, impl),
                  OPC(and, absY),
                  INV,
                  INV,
                  INV,
                  OPC(and, absX),
                  OPC(rol, absX),
                  INV,
                  OPC(rti, impl),
                  OPC(eor, Xind),
                  INV,
                  INV,
                  INV,
                  OPC(eor, zpg),
                  OPC(lsr, zpg),
                  INV,
                  OPC(pha, impl),
                  OPC(eor, imm),
                  OPC(lsr_a, A),
                  INV,
                  OPC(jmp, abs),
                  OPC(eor, abs),
                  OPC(lsr, abs),
                  INV,
                  OPC(bvc, rel),
                  OPC(eor, indY),
                  INV,
                  INV,
                  INV,
                  OPC(eor, zpgX),
                  OPC(lsr, zpgX),
                  INV,
                  OPC(cli, impl),
                  OPC(eor, absY),
                  INV,
                  INV,
                  INV,
                  OPC(eor, absX),
                  OPC(lsr, absX),
                  INV,
                  OPC(rts, impl),
                  OPC(adc, Xind),
                  INV,
                  INV,
                  INV,
                  OPC(adc, zpg),
                  OPC(ror, zpg),
                  INV,
                  OPC(pla, impl),
                  OPC(adc, imm),
                  OPC(ror_a, A),
                  INV,
                  OPC(jmp, ind),
                  OPC(adc, abs),
                  OPC(ror, abs),
                  INV,
                  OPC(bvs, rel),
                  OPC(adc, indY),
                  INV,
                  INV,
                  INV,
                  OPC(adc, zpgX),
                  OPC(ror, zpgX),
                  INV,
                  OPC(sei, impl),
                  OPC(adc, absY),
                  INV,
                  INV,
                  INV,
                  OPC(adc, absX),
                  OPC(ror, absX),
                  INV,
                  INV,
                  OPC(sta, Xind),
                  INV,
                  INV,
                  OPC(sty, zpg),
                  OPC(sta, zpg),
                  OPC(stx, zpg),
                  INV,
                  OPC(dey, impl),
                  INV,
                  OPC(txa, impl),
                  INV,
                  OPC(sty, abs),
                  OPC(sta, abs),
                  OPC(stx, abs),
                  INV,
                  OPC(bcc, rel),
                  OPC(sta, indY),
                  INV,
                  INV,
                  OPC(sty, zpgX),
                  OPC(sta, zpgX),
                  OPC(stx, zpgY),
                  INV,
                  OPC(tya, impl),
                  OPC(sta, absY),
                  OPC(txs, impl),
                  INV,
                  INV,
                  OPC(sta, absX),
                  INV,
                  INV,
                  OPC(ldy, imm),
                  OPC(lda, Xind),
                  OPC(ldx, imm),
                  INV,
                  OPC(ldy, zpg),
                  OPC(lda, zpg),
                  OPC(ldx, zpg),
                  INV,
                  OPC(tay, impl),
                  OPC(lda, imm),
                  OPC(tax, impl),
                  INV,
                  OPC(ldy, abs),
                  OPC(lda, abs),
                  OPC(ldx, abs),
                  INV,
                  OPC(bcs, rel),
                  OPC(lda, indY),
                  INV,
                  INV,
                  OPC(ldy, zpgX),
                  OPC(lda, zpgX),
                  OPC(ldx, zpgY),
                  INV,
                  OPC(clv, impl),
                  OPC(lda, absY),
                  OPC(tsx, impl),
                  INV,
                  OPC(ldy, absX),
                  OPC(lda, absX),
                  OPC(ldx, absY),
                  INV,
                  OPC(cpy, imm),
                  OPC(cmp, Xind),
                  INV,
                  INV,
                  OPC(cpy, zpg),
                  OPC(cmp, zpg),
                  OPC(dec, zpg),
                  INV,
                  OPC(iny, impl),
                  OPC(cmp, imm),
                  OPC(dex, impl),
                  INV,
                  OPC(cpy, abs),
                  OPC(cmp, abs),
                  OPC(dec, abs),
                  INV,
                  OPC(bne, rel),
                  OPC(cmp, indY),
                  INV,
                  INV,
                  INV,
                  OPC(cmp, zpgX),
                  OPC(dec, zpgX),
                  INV,
                  OPC(cld, impl),
                  OPC(cmp, absY),
                  INV,
                  INV,
                  INV,
                  OPC(cmp, absX),
                  OPC(dec, absX),
                  INV,
                  OPC(cpx, imm),
                  OPC(sbc, Xind),
                  INV,
                  INV,
                  OPC(cpx, zpg),
                  OPC(sbc, zpg),
                  OPC(inc, zpg),
                  INV,
                  OPC(inx, impl),
                  OPC(sbc, imm),
                  OPC(nop, impl),
                  OPC(sbc, imm),
                  OPC(cpx, abs),
                  OPC(sbc, abs),
                  OPC(inc, abs),
                  INV,
                  OPC(beq, rel),
                  OPC(sbc, indY),
                  INV,
                  INV,
                  INV,
                  OPC(sbc, zpgX),
                  OPC(inc, zpgX),
                  INV,
                  OPC(sed, impl),
                  OPC(sbc, absY),
                  INV,
                  INV,
                  INV,
                  OPC(sbc, absX),
                  OPC(inc, absX),
                  INV

};

char *debug_codes[] = {
    "BRK",  "ORA",  "NULL", "NULL", "NULL", "ORA",  "ASL",  "NULL", "PHP",
    "ORA",  "ASL",  "NULL", "NULL", "ORA",  "ASL",  "NULL", "BPL",  "ORA",
    "NULL", "NULL", "NULL", "ORA",  "ASL",  "NULL", "CLC",  "ORA",  "NULL",
    "NULL", "NULL", "ORA",  "ASL",  "NULL", "JSR",  "AND",  "NULL", "NULL",
    "BIT",  "AND",  "ROL",  "NULL", "PLP",  "AND",  "ROL",  "NULL", "BIT",
    "AND",  "ROL",  "NULL", "BMI",  "AND",  "NULL", "NULL", "NULL", "AND",
    "ROL",  "NULL", "SEC",  "AND",  "NULL", "NULL", "NULL", "AND",  "ROL",
    "NULL", "RTI",  "EOR",  "NULL", "NULL", "NULL", "EOR",  "LSR",  "NULL",
    "PHA",  "EOR",  "LSR",  "NULL", "JMP",  "EOR",  "LSR",  "NULL", "BVC",
    "EOR",  "NULL", "NULL", "NULL", "EOR",  "LSR",  "NULL", "CLI",  "EOR",
    "NULL", "NULL", "NULL", "EOR",  "LSR",  "NULL", "RTS",  "ADC",  "NULL",
    "NULL", "NULL", "ADC",  "ROR",  "NULL", "PLA",  "ADC",  "ROR",  "NULL",
    "JMP",  "ADC",  "ROR",  "NULL", "BVS",  "ADC",  "NULL", "NULL", "NULL",
    "ADC",  "ROR",  "NULL", "SEI",  "ADC",  "NULL", "NULL", "NULL", "ADC",
    "ROR",  "NULL", "NULL", "STA",  "NULL", "NULL", "STY",  "STA",  "STX",
    "NULL", "DEY",  "NULL", "TXA",  "NULL", "STY",  "STA",  "STX",  "NULL",
    "BCC",  "STA",  "NULL", "NULL", "STY",  "STA",  "STX",  "NULL", "TYA",
    "STA",  "TXS",  "NULL", "NULL", "STA",  "NULL", "NULL", "LDY",  "LDA",
    "LDX",  "NULL", "LDY",  "LDA",  "LDX",  "NULL", "TAY",  "LDA",  "TAX",
    "NULL", "LDY",  "LDA",  "LDX",  "NULL", "BCS",  "LDA",  "NULL", "NULL",
    "LDY",  "LDA",  "LDX",  "NULL", "CLV",  "LDA",  "TSX",  "NULL", "LDY",
    "LDA",  "LDX",  "NULL", "CPY",  "CMP",  "NULL", "NULL", "CPY",  "CMP",
    "DEC",  "NULL", "INY",  "CMP",  "DEX",  "NULL", "CPY",  "CMP",  "DEC",
    "NULL", "BNE",  "CMP",  "NULL", "NULL", "NULL", "CMP",  "DEC",  "NULL",
    "CLD",  "CMP",  "NULL", "NULL", "NULL", "CMP",  "DEC",  "NULL", "CPX",
    "SBC",  "NULL", "NULL", "CPX",  "SBC",  "INC",  "NULL", "INX",  "SBC",
    "NOP",  "NULL", "CPX",  "SBC",  "INC",  "NULL", "BEQ",  "SBC",  "NULL",
    "NULL", "NULL", "SBC",  "INC",  "NULL", "SED",  "SBC",  "NULL", "NULL",
    "NULL", "SBC",  "INC",  "NULL"
};

#endif // OPCODES_H_
